es_name: "NEATBackprop"
problem_type: "binary_classification"

normalize: false
pop_size: 64
max_hidden_nodes: 32
propagation_steps: null
output_base: "log/NEAT_backprop/binary_classification/xor_v7"

problem_config:
  dataset_type: "xor"
  train_size: 512
  test_size: 512
  dataset_noise: 0.10
  dataset_seed: 42
  batch_size: 64
  grid_range: [-6.0, 6.0]
  grid_resolution: 200

es_config:
  pop_size: 64
  n_input: 2
  n_output: 1
  max_hidden_nodes: 32
  activation_choices: [1, 3, 4, 5, 6, 7, 9, 10, 11]
  init_activation: 9
 
  grad_steps: 16
  learning_rate: 0.005
  batch_size: 64

  dataset_type: "xor"
  train_size: 512
  test_size: 512
  dataset_noise: 0.10
  dataset_seed: 42

  prob_add_conn: 0.6
  prob_add_node: 0.1
  prob_crossover: 0.4
  prob_enable: 0.2
  prob_mut_conn: 0.0
  prob_mut_act: 0.1
  prob_init_enable: 1.0

  select_cull_ratio: 0.1
  select_elite_ratio: 0.1
  select_tourn_size: 2

  spec_compat_mod: 0.2
  spec_drop_off_age: 40
  spec_target: 5
  spec_thresh: 2.5
  spec_thresh_min: 1.5
  spec_gene_coef: 1.0
  spec_weight_coef: 0.4

  ann_abs_w_cap: 5.0
  alg_prob_moo: 0.2

max_iter: 30
log_interval: 1
test_interval: 10
n_repeats: 2
num_tests: 64

seed: 42
gpu_id: [0, 1, 2, 3]
debug: false
run_name: "default"
