es_name: "NEAT"
problem_type: "slimevolley"
normalize: false
pop_size: 128
max_hidden_nodes: 64
propagation_steps: 64
es_config:
  pop_size: 128
  n_input: 12
  n_output: 3
  max_hidden_nodes: 64
  activation_choices: [1, 5, 9]
  prob_add_conn: 0.05
  prob_add_node: 0.03
  prob_crossover: 0.8
  prob_enable: 0.01
  prob_mut_conn: 0.8
  prob_mut_act: 0.05
  prob_init_enable: 1.0
  select_cull_ratio: 0.1
  select_elite_ratio: 0.1
  select_tourn_size: 2
  spec_compat_mod: 0.25
  spec_drop_off_age: 64
  spec_target: 6
  spec_thresh: 3.0
  spec_thresh_min: 1.0
  spec_gene_coef: 1.0
  spec_weight_coef: 0.5
  ann_abs_w_cap: 5.0
max_iter: 1000
log_interval: 5
test_interval: 100
n_repeats: 16
num_tests: 100
seed: 42
gpu_id: [0]
debug: false
