es_name: "NEAT"
problem_type: "slimevolley"
env_name: "greedy"

normalize: false
pop_size: 256
max_hidden_nodes: 64
propagation_steps: 64

es_config:
  pop_size: 256
  n_input: 12
  n_output: 3

  max_hidden_nodes: 64
  activation_choices: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

  prob_add_conn: 0.4
  prob_add_node: 0.4
  prob_crossover: 0.5
  prob_enable: 0.1
  prob_mut_conn: 0.2
  prob_mut_act: 0.2
  prob_init_enable: 0.9

  select_cull_ratio: 0.25
  select_elite_ratio: 0.25
  select_tourn_size: 3

  spec_compat_mod: 0.2
  spec_drop_off_age: 32
  spec_target: 5
  spec_thresh: 3
  spec_thresh_min: 1.2
  spec_gene_coef: 1.1
  spec_weight_coef: 0.6
  ann_abs_w_cap: 3.0
  alg_prob_moo: 0.5

max_iter: 1000
log_interval: 5
test_interval: 100
n_repeats: 8
num_tests: 100

seed: 42
gpu_id: [0, 1]
debug: false